### ISSUE TITLE
Project status & docs

### ISSUE THREAD

**Issue by michaeljs1990** [praekeltfoundation/vault-plugin-auth-mesos#12]
Hey sorry to open an issue for this but just had a few questions about the project.

1. It hasn't been updated in a bit are you still using this and have you run into any issues?
2. How does the feature set compare to https://github.com/nemosupremo/vault-gatekeeper and have you used it?
3. Do any simple docs exist with an example use of this vault auth plugin?
4. Does this support multiple mesos clusters out of the box?

**Comment by jerith** [comment]
Sorry for the long delay -- I've been away from work for several weeks.

1. This plugin is somewhere between "prototype" and "production-ready". We've tested it in one of our experimental clusters, but it's part of a bigger system that involves several other moving parts and we haven't solved all the problems in those yet. (We don't have very much internal capacity to work on this stuff, so movement is much slower than we'd like.)

2. We started with Gatekeeper, but it was operationally complex and there were several reasons we couldn't use it as-is (although I don't remember what they were). We eventually decided that writing an auth plugin would require about the same amount of effort as making Gatekeeper fit our requirements and would have a much lower operational cost when deployed.

3. Not really, I'm sorry to say. We didn't want to spend too much time working on documentation that would likely change as we tested the plugin and improved its APIs, and then other work bumped this way down our priority queue.

4. No, and we don't even (currently) support multiple Mesos URLs for failover (see #10). We prefer to keep our clusters as isolated as possible (so each cluster has its own Vault deployment), but it should be straightforward to set up a backend mount for each cluster. They'd each have their own state and configuration, so anything shared would have to be duplicated.

It doesn't look like we'll be picking up work on this again any time soon, but it basically does what we need it to do and I definitely think it's worth trying out if it looks like it'll be useful to you. While we're not in a position to look at feature requests or large contributions, we're happy to accept smallish pull requests, bugfixes, and docs. You're also very welcome to fork the repo and build on what we've done so far -- we chose a very permissive license specifically to make that easy.

**Comment by michaeljs1990** [comment]
@jerith no problem and thank you for the reply. The complexity of setting up the gatekeeper plugin was something that put me off to it as well which is how I ended up here. I'm glad to hear that the existing implementation is working well in which case i'll give this a go and contribute some docs back upstream. Mounting multiple backends for the different clusters sounds perfectly reasonable although I may want to add #10. 

Thanks again
